spring:
    datasource:
        url: jdbc:mysql://localhost:3306/transporter?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    #redis配置信息
    redis: 
       host : 127.0.0.1
       port : 6379
       max-idle : 8
       min-idle : 0
#配置文件相关目录
upload:
    filePath: D:/data/ifly
    


